env:
  node: true
  es6: true
  mocha: true
parser: "@typescript-eslint/parser"
plugins:
  - prettier
  - "@typescript-eslint"
rules:
  prettier/prettier: error
  "@typescript-eslint/no-var-requires": 1
  no-console: 1
  no-unsafe-optional-chaining: 2
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:mocha/recommended
ignorePatterns: [
  "/dist/**/*"
]
