ui: tdd
extension:
  - js
  - ts
watch: false
watch-files:
  - 'server/**/*.js'
  - 'test/**/*.js'
  - 'server/**/*.ts'
  - 'test/**/*.ts'
package: "tsconfig.json"
require:
  - ts-node/register
  - test/hooks.ts